
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS fb_name TEXT,
  ADD COLUMN IF NOT EXISTS contact_number TEXT,
  ADD COLUMN IF NOT EXISTS fb_profile_link TEXT,
  ADD COLUMN IF NOT EXISTS dob DATE,
  ADD COLUMN IF NOT EXISTS district TEXT,
  ADD COLUMN IF NOT EXISTS current_location TEXT,
  ADD COLUMN IF NOT EXISTS playing_device TEXT,
  ADD COLUMN IF NOT EXISTS konami_uid TEXT,
  ADD COLUMN IF NOT EXISTS blood_group TEXT;

ALTER TABLE public.registrations
  ADD COLUMN IF NOT EXISTS fb_post_link TEXT;

ALTER TABLE public.match_submissions
  ADD COLUMN IF NOT EXISTS leg1_p1 INTEGER,
  ADD COLUMN IF NOT EXISTS leg1_p2 INTEGER,
  ADD COLUMN IF NOT EXISTS leg2_p1 INTEGER,
  ADD COLUMN IF NOT EXISTS leg2_p2 INTEGER,
  ADD COLUMN IF NOT EXISTS decider_p1 INTEGER,
  ADD COLUMN IF NOT EXISTS decider_p2 INTEGER;
